version: '3'
services:
  postgresql:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=example
    ports:
      - '5432:5432'
